# What You Will Learn:
Core NumPy operations including array creation, manipulation, and basic array operations.
Skills in handling one-dimensional and multi-dimensional arrays.


# What You Will Create:
A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.


## Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

# Expected Output:



array([3, 2, 0, 1, 2])

In [4]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


## Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array = np.arange(1, 10)
reshape_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshape_array)


Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [6]:
array = np.random.rand(4, 5).round(2)

print(array)


[[0.6  0.85 0.17 0.5  0.42]
 [0.25 0.01 0.58 0.   0.22]
 [0.18 0.93 0.84 0.38 0.1 ]
 [0.5  0.05 0.04 0.51 0.83]]


## Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [10]:
array = np.array([[21, 22, 23, 22, 22],
                [20, 21, 22, 23, 24],
                [21, 22, 23, 22, 22]])

second_row = array[1]
print(second_row)

[20 21 22 23 24]


## Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
arr = np.arange(10)
reversed_arr = arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


## Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
total_sum = np.sum(arr)
average = np.mean(arr)
print("Sum:", total_sum)
print("Average:", average)

Sum: 45
Average: 4.5


## Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
matrix = np.arange(1, 21).reshape(4, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
